### ISSUE TITLE
Atom not reporting sizes because of decorator error

### ISSUE THREAD

**Issue by tbremer** [IanMitchell/import-cost-atom#8]
Atom is not reporting sizes because of an error in the package.

This could be an error with import-cost, but I figured I would start here and move upward.

Error below:
<details>

```javascript
events.js:116 Error: The 'decorators' plugin requires a 'decoratorsBeforeExport' option, whose value must be a boolean.
    at validatePlugins (/Users/bremert/.atom/packages/atom-import-cost/node_modules/@babel/parser/lib/index.js:10407:13)
    at getParser (/Users/bremert/.atom/packages/atom-import-cost/node_modules/@babel/parser/lib/index.js:10464:5)
    at parse (/Users/bremert/.atom/packages/atom-import-cost/node_modules/@babel/parser/lib/index.js:10448:12)
    at parse (/Users/bremert/.atom/packages/atom-import-cost/node_modules/import-cost/dist/src/jsParser.js:51:28)
    at getPackages (/Users/bremert/.atom/packages/atom-import-cost/node_modules/import-cost/dist/src/jsParser.js:45:13)
    at getPackages (/Users/bremert/.atom/packages/atom-import-cost/node_modules/import-cost/dist/src/parser.js:18:38)
    at _callee$ (/Users/bremert/.atom/packages/atom-import-cost/node_modules/import-cost/dist/src/index.js:41:47)
    at tryCatch (/Users/bremert/.atom/packages/atom-import-cost/node_modules/babel-runtime/node_modules/regenerator-runtime/runtime.js:62:40)
    at Generator.invoke [as _invoke] (/Users/bremert/.atom/packages/atom-import-cost/node_modules/babel-runtime/node_modules/regenerator-runtime/runtime.js:296:22)
    at Generator.prototype.(anonymous function) [as next] (/Users/bremert/.atom/packages/atom-import-cost/node_modules/babel-runtime/node_modules/regenerator-runtime/runtime.js:114:21)
    at step (/Users/bremert/.atom/packages/atom-import-cost/node_modules/import-cost/dist/src/index.js:21:191)
    at /Users/bremert/.atom/packages/atom-import-cost/node_modules/import-cost/dist/src/index.js:21:437
    at new Promise (<anonymous>)
    at /Users/bremert/.atom/packages/atom-import-cost/node_modules/import-cost/dist/src/index.js:21:99
emitOne @ events.js:116
emit @ events.js:211
_callee$ @ /Users/bremert/.atom/packages/atom-import-cost/node_modules/import-cost/dist/src/index.js:72
tryCatch @ /Users/bremert/.atom/packages/atom-import-cost/node_modules/babel-runtime/node_modules/regenerator-runtime/runtime.js:62
invoke @ /Users/bremert/.atom/packages/atom-import-cost/node_modules/babel-runtime/node_modules/regenerator-runtime/runtime.js:296
prototype.(anonymous function) @ /Users/bremert/.atom/packages/atom-import-cost/node_modules/babel-runtime/node_modules/regenerator-runtime/runtime.js:114
step @ /Users/bremert/.atom/packages/atom-import-cost/node_modules/import-cost/dist/src/index.js:21
(anonymous) @ /Users/bremert/.atom/packages/atom-import-cost/node_modules/import-cost/dist/src/index.js:21
(anonymous) @ /Users/bremert/.atom/packages/atom-import-cost/node_modules/import-cost/dist/src/index.js:21
setTimeout (async)
importCost @ /Users/bremert/.atom/packages/atom-import-cost/node_modules/import-cost/dist/src/index.js:34
calculateCost @ import-cost-atom.js? [sm]:65
(anonymous) @ import-cost-atom.js? [sm]:34
module.exports.Emitter.simpleDispatch @ commitCommentView_item.graphql.js:112
module.exports.Emitter.emit @ commitCommentView_item.graphql.js:112
(anonymous) @ commitCommentView_item.graphql.js:112
Promise resolved (async)
module.exports.TextBuffer.saveTo @ commitCommentView_item.graphql.js:112
module.exports.TextBuffer.save @ commitCommentView_item.graphql.js:112
save @ commitCommentView_item.graphql.js:112
_safeFormatCodeOnSave.takeUntil.toPromise.then @ /Users/bremert/.atom/packages/atom-ide-ui/modules/atom-ide-ui/pkg/atom-ide-code-format/lib/CodeFormatManager.js:174
Promise resolved (async)
editor_.save @ /Users/bremert/.atom/packages/atom-ide-ui/modules/atom-ide-ui/pkg/atom-ide-code-format/lib/CodeFormatManager.js:174
promisify @ commitCommentView_item.graphql.js:112
promisify @ commitCommentView_item.graphql.js:112
saveItem @ commitCommentView_item.graphql.js:112
saveActiveItem @ commitCommentView_item.graphql.js:112
saveActivePaneItem @ commitCommentView_item.graphql.js:112
core:save @ commitCommentView_item.graphql.js:112
handleCommandEvent @ commitCommentView_item.graphql.js:112
module.exports.KeymapManager.dispatchCommandEvent @ commitCommentView_item.graphql.js:112
module.exports.KeymapManager.handleKeyboardEvent @ commitCommentView_item.graphql.js:112
handleDocumentKeyEvent @ commitCommentView_item.graphql.js:112
```

**Comment by IanMitchell** [comment]
Hey! I think you have the wrong repo - judging from the stacktrace you’re using an alternative implementation from here I think:

https://atom.io/users/siddharthkp

**Comment by tbremer** [comment]
Oh jeez, this is embarrassing. So sorry!

**Comment by IanMitchell** [comment]
All good! Good way to see if it's the Atom plugin or the import-cost lib is to give mine a shot and see if it also fails though!

**Comment by tbremer** [comment]
That's exactly what I did, and I got the same error.

So I opened an issue with them here: https://github.com/wix/import-cost/issues/81
